### ISSUE TITLE
some smallimageNet training questions

### ISSUE THREAD

**Issue by jiajunhua** [jeffdonahue/bigan#6]
Firstly, thank you for sharing your great works and sorry for my poor English.

I have a question about  smallimageNet. Pictures pixels are 64*64 ,I change train_imagenet.sh the 19 line's raw_size to 64,then run train_imagenet.sh ,some mistakes happened in follows: 
Pre-sized data not found (./data/imagenet64); using original data: ./data/imagenet
Traceback (most recent call last):
  File "train_gan.py", line 262, in <module>
    dataset = data.Dataset(args)
  File "/home/hddsj/bigan-master/data.py", line 453, in __init__
    max_images=args.max_images)
  File "/home/hddsj/bigan-master/data.py", line 210, in imagenet_data_providers
    assert 0 <= num_test <= len(data['val'])
AssertionError
Then run resize_imageset.py some errors appears，in follows:
usage: resize_imageset.py [-h] [-c] [-f FORMAT] [-q] [-j JOBS] [-r] [-o]
                          size input_directory output_directory
resize_imageset.py: error: too few arguments

How can I input these arguments  ???  

 What does the following code in Readme mean ??? 
SIZE=72  # or SIZE=128 for generalized BiGAN experiments
# "-j 4" uses 4 resizing processes
python resize_imageset.py -r -j 4 ${SIZE} ./data/imagenet ./data/imagenet${SIZE}

**Comment by jiajunhua** [comment]
Thank you very much!  My email is 939634770@qq.com
I looking forward for your reply.
